### ISSUE TITLE
Include a reliability analysis

### ISSUE THREAD

**Issue by riking** [cloudflare/ct-log#1]
In order to have 99% reliability for a service, you cannot use 2 services with 99% reliability each: you need to multiply the percentages together, resulting in 98% uptime (or, easier: just add together the difference from 100%, assuming independent failures probably won't overlap; this will end up underestimating your reliability).

Use the reliability commitments, outage histories, and any other available information of each used service to come up with an analysis.

**Comment by Bren2010** [comment]
I'm not able to reason about this easily.

DigitalOcean and Backblaze have 99.9% uptime SLAs. Cloudflare has no SLA, but we'll call it 99.9%. So if the only failure mode is "a provider becomes temporarily unresponsive", then the uptime of the log is lower-bounded by 99.7%.

But there are other failure modes where the service provider could claim to still be upholding their SLA, and a lot of uncertainty about their likelihood. Some are inconvenient: one service provider fires the log operator for abuse and doesn't give them time to migrate. Most are fatal: any form of data loss / corruption / rollback.

**Comment by Bren2010** [comment]
My deployment of this codebase has had a period of stability, where there were no outages caused by my own negligence. Merkle Town has this profile of the log:

**Uptime:** 99.7%

| Endpoint | &nbsp; |
|----------|---|
| add-chain (new) | 99.8% |
| add-chain (old) | 99.5% |
| add-pre-chain (new) | 99.7% |
| add-pre-chain (old) | 99.6% |
| get-entries | 99.7% |
| get-roots | 99.9% |
| get-sth | 100% |

**Response time:** 861ms

| Endpoint | &nbsp; |
|----------|---|
| add-chain (new) | 278ms |
| add-chain (old) | 1.9s |
| add-pre-chain (new) | 246ms |
| add-pre-chain (old) | 1.8s |
| get-entries | 1.7s |
| get-roots | 54ms |
| get-sth | 24ms |

Hope this answers your question.
